<a href="https://colab.research.google.com/github/RIDIHI9/mcabigdata/blob/main/assgn2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])

# using shortcut method to reverse
res = np.flip(ini_array)

# printing result
print("final array", str(res))


final array [5 4 6 3 2 1]


In [2]:
import numpy as np

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

comparison = an_array == another_array
equal_arrays = comparison.all()

print(equal_arrays)

True


In [3]:
import numpy as np

arr = np.array([1,2,2,3,4,3,5,5,5])
print("Original array:")
print(arr)

print("Most frequent value in the above array:")
print(np.bincount(arr).argmax())

Original array:
[1 2 2 3 4 3 5 5 5]
Most frequent value in the above array:
5


In [4]:
import numpy as np


arr = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


total_sum = np.sum(arr)


row_sum = np.sum(arr, axis=1)

col_sum = np.sum(arr, axis=0)

print("Matrix:")
print(arr)

print("\ni. Sum of all elements:", total_sum)

print("\nii. Sum of all elements row-wise:")
print(row_sum)

print("\niii. Sum of all elements column-wise:")
print(col_sum)

Matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

i. Sum of all elements: 45

ii. Sum of all elements row-wise:
[[14]
 [16]
 [15]]

iii. Sum of all elements column-wise:
[[20  9 16]]
